// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object KlaviyoFlutterMessengerPigeonUtils {
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** An enum representing a notification setting for this app on the device. */
enum class KlaviyoAppleNotificationSetting(val raw: Int) {
  /** This setting is currently disabled by the user. */
  DISABLED(0),
  /** This setting is currently enabled. */
  ENABLED(1),
  /**
   * This setting is not supported on this device.
   *
   * Usually this means that the iOS version required for this setting has not been met,
   * or the platform is not Apple.
   */
  NOT_SUPPORTED(2);

  companion object {
    fun ofRaw(raw: Int): KlaviyoAppleNotificationSetting? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** An enum representing the show previews notification setting for this app on the device. */
enum class KlaviyoAppleShowPreviewSetting(val raw: Int) {
  /** Always show previews even if the device is currently locked. */
  ALWAYS(0),
  /** Never show previews. */
  NEVER(1),
  /**
   * This setting is not supported on this device.
   *
   * Usually this means that the iOS version required for this setting (iOS 11+) has not been met,
   * or the platform is not Apple.
   */
  NOT_SUPPORTED(2),
  /** Only show previews when the device is unlocked. */
  WHEN_AUTHENTICATED(3);

  companion object {
    fun ofRaw(raw: Int): KlaviyoAppleShowPreviewSetting? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Represents the current status of the platforms notification permissions. */
enum class KlaviyoAuthorizationStatus(val raw: Int) {
  /** The app is authorized to create notifications. */
  AUTHORIZED(0),
  /** The app is not authorized to create notifications. */
  DENIED(1),
  /**
   * The app user has not yet chosen whether to allow the application to create
   * notifications. Usually this status is returned prior to the first call
   * of [requestPermission].
   */
  NOT_DETERMINED(2),
  /** The app is currently authorized to post non-interrupting user notifications. */
  PROVISIONAL(3);

  companion object {
    fun ofRaw(raw: Int): KlaviyoAuthorizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * An enum representing a notification priority on Android.
 *
 * Note; on devices which have channel support (Android 8.0 (API level 26) +),
 * this value will be ignored. Instead, the channel "importance" level is used.
 */
enum class KlaviyoAndroidNotificationPriority(val raw: Int) {
  /**
   * The application small icon will not show up in the status bar, or alert the user. The notification
   * will be in a collapsed state in the notification shade and placed at the bottom of the list.
   */
  MINIMUM_PRIORITY(0),
  /**
   * The application small icon will show in the device status bar, however the notification will
   * not alert the user (no sound or vibration). The notification will show in it's expanded state
   * when the notification shade is pulled down.
   */
  LOW_PRIORITY(1),
  /**
   * When a notification is received, the device smallIcon will appear in the notification shade.
   * When the user pulls down the notification shade, the content of the notification will be shown
   * in it's expanded state.
   */
  DEFAULT_PRIORITY(2),
  /**
   * Notifications will appear on-top of applications, allowing direct interaction without pulling
   * own the notification shade. This level is used for urgent notifications, such as
   * incoming phone calls, messages etc, which require immediate attention.
   */
  HIGH_PRIORITY(3),
  /** The highest priority level a notification can be set to. */
  MAXIMUM_PRIORITY(4);

  companion object {
    fun ofRaw(raw: Int): KlaviyoAndroidNotificationPriority? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KlaviyoRemoteMessage (
  /** The ID of the upstream sender location. */
  val senderId: String? = null,
  /** The iOS category this notification is assigned to. */
  val category: String? = null,
  /** The collapse key a message was sent with. Used to override existing messages with the same key. */
  val collapseKey: String? = null,
  /** Whether the iOS APNs message was configured as a background update notification. */
  val contentAvailable: Boolean,
  /** Any additional data sent with the message. */
  val data: Map<String?, Any?>,
  /** The topic name or message identifier. */
  val from: String? = null,
  /** A unique ID assigned to every message. */
  val messageId: String? = null,
  /** The message type of the message. */
  val messageType: String? = null,
  /**
   * Whether the iOS APNs `mutable-content` property on the message was set
   * allowing the app to modify the notification via app extensions.
   */
  val mutableContent: Boolean,
  /** Additional Notification data sent with the message. */
  val notification: KlaviyoRemoteNotification? = null,
  /** The time the message was sent, represented as a [String]. */
  val sentTime: String? = null,
  /** An iOS app specific identifier used for notification grouping. */
  val threadId: String? = null,
  /** The time to live for the message in seconds. */
  val ttl: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KlaviyoRemoteMessage {
      val senderId = pigeonVar_list[0] as String?
      val category = pigeonVar_list[1] as String?
      val collapseKey = pigeonVar_list[2] as String?
      val contentAvailable = pigeonVar_list[3] as Boolean
      val data = pigeonVar_list[4] as Map<String?, Any?>
      val from = pigeonVar_list[5] as String?
      val messageId = pigeonVar_list[6] as String?
      val messageType = pigeonVar_list[7] as String?
      val mutableContent = pigeonVar_list[8] as Boolean
      val notification = pigeonVar_list[9] as KlaviyoRemoteNotification?
      val sentTime = pigeonVar_list[10] as String?
      val threadId = pigeonVar_list[11] as String?
      val ttl = pigeonVar_list[12] as Long?
      return KlaviyoRemoteMessage(senderId, category, collapseKey, contentAvailable, data, from, messageId, messageType, mutableContent, notification, sentTime, threadId, ttl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      senderId,
      category,
      collapseKey,
      contentAvailable,
      data,
      from,
      messageId,
      messageType,
      mutableContent,
      notification,
      sentTime,
      threadId,
      ttl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KlaviyoRemoteMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return KlaviyoFlutterMessengerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KlaviyoRemoteNotification (
  /** Android specific notification properties. */
  val android: KlaviyoAndroidNotification? = null,
  /** Apple specific notification properties. */
  val apple: KlaviyoAppleNotification? = null,
  /** Web specific notification properties. */
  val web: KlaviyoWebNotification? = null,
  /** The notification title. */
  val title: String? = null,
  /** Any arguments that should be formatted into the resource specified by titleLocKey. */
  val titleLocArgs: List<String>,
  /** The native localization key for the notification title. */
  val titleLocKey: String? = null,
  /** The notification body content. */
  val body: String? = null,
  /** Any arguments that should be formatted into the resource specified by bodyLocKey. */
  val bodyLocArgs: List<String>,
  /** The native localization key for the notification body content. */
  val bodyLocKey: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KlaviyoRemoteNotification {
      val android = pigeonVar_list[0] as KlaviyoAndroidNotification?
      val apple = pigeonVar_list[1] as KlaviyoAppleNotification?
      val web = pigeonVar_list[2] as KlaviyoWebNotification?
      val title = pigeonVar_list[3] as String?
      val titleLocArgs = pigeonVar_list[4] as List<String>
      val titleLocKey = pigeonVar_list[5] as String?
      val body = pigeonVar_list[6] as String?
      val bodyLocArgs = pigeonVar_list[7] as List<String>
      val bodyLocKey = pigeonVar_list[8] as String?
      return KlaviyoRemoteNotification(android, apple, web, title, titleLocArgs, titleLocKey, body, bodyLocArgs, bodyLocKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      android,
      apple,
      web,
      title,
      titleLocArgs,
      titleLocKey,
      body,
      bodyLocArgs,
      bodyLocKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KlaviyoRemoteNotification) {
      return false
    }
    if (this === other) {
      return true
    }
    return KlaviyoFlutterMessengerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Android specific properties of a [KlaviyoRemoteNotification].
 *
 * This will only be populated if the current device is Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KlaviyoAndroidNotification (
  /** The channel the notification is delivered on. */
  val channelId: String? = null,
  /**
   * A spcific click action was defined for the notification.
   *
   * This property is not required to handle user interaction.
   */
  val clickAction: String? = null,
  /** The color of the notification. */
  val color: String? = null,
  /** The current notification count for the application. */
  val count: Long? = null,
  /**
   * The image URL for the notification.
   *
   * Will be `null` if the notification did not include an image.
   */
  val imageUrl: String? = null,
  val link: String? = null,
  /**
   * The priority for the notifcation.
   *
   * This property only has impact on devices running Android 8.0 (API level 26) +.
   * Later than this, they use the channel importance instead.
   */
  val priority: KlaviyoAndroidNotificationPriority,
  /** The resource file name of the small icon shown in the notification. */
  val smallIcon: String? = null,
  /** The resource file name of the sound used to alert users to the incoming notification. */
  val sound: String? = null,
  /** Ticker text for the notification, used for accessibility purposes. */
  val ticker: String? = null,
  /** The tag of the notification. */
  val tag: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KlaviyoAndroidNotification {
      val channelId = pigeonVar_list[0] as String?
      val clickAction = pigeonVar_list[1] as String?
      val color = pigeonVar_list[2] as String?
      val count = pigeonVar_list[3] as Long?
      val imageUrl = pigeonVar_list[4] as String?
      val link = pigeonVar_list[5] as String?
      val priority = pigeonVar_list[6] as KlaviyoAndroidNotificationPriority
      val smallIcon = pigeonVar_list[7] as String?
      val sound = pigeonVar_list[8] as String?
      val ticker = pigeonVar_list[9] as String?
      val tag = pigeonVar_list[10] as String?
      return KlaviyoAndroidNotification(channelId, clickAction, color, count, imageUrl, link, priority, smallIcon, sound, ticker, tag)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      channelId,
      clickAction,
      color,
      count,
      imageUrl,
      link,
      priority,
      smallIcon,
      sound,
      ticker,
      tag,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KlaviyoAndroidNotification) {
      return false
    }
    if (this === other) {
      return true
    }
    return KlaviyoFlutterMessengerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Apple specific properties of a [KlaviyoRemoteNotification].
 *
 * This will only be populated if the current device is Apple based (iOS/MacOS).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KlaviyoAppleNotification (
  /** The value which sets the application badge. */
  val badge: String? = null,
  /** Sound values for the incoming notification. */
  val sound: KlaviyoAppleNotificationSound? = null,
  /**
   * The image URL for the notification.
   *
   * Will be `null` if the notification did not include an image.
   */
  val imageUrl: String? = null,
  /** Any subtile text on the notification. */
  val subtitle: String? = null,
  /** Any arguments that should be formatted into the resource specified by subtitleLocKey. */
  val subtitleLocArgs: List<String>,
  /** The native localization key for the notification subtitle. */
  val subtitleLocKey: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KlaviyoAppleNotification {
      val badge = pigeonVar_list[0] as String?
      val sound = pigeonVar_list[1] as KlaviyoAppleNotificationSound?
      val imageUrl = pigeonVar_list[2] as String?
      val subtitle = pigeonVar_list[3] as String?
      val subtitleLocArgs = pigeonVar_list[4] as List<String>
      val subtitleLocKey = pigeonVar_list[5] as String?
      return KlaviyoAppleNotification(badge, sound, imageUrl, subtitle, subtitleLocArgs, subtitleLocKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      badge,
      sound,
      imageUrl,
      subtitle,
      subtitleLocArgs,
      subtitleLocKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KlaviyoAppleNotification) {
      return false
    }
    if (this === other) {
      return true
    }
    return KlaviyoFlutterMessengerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Represents the sound property for [KlaviyoAppleNotification]
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KlaviyoAppleNotificationSound (
  /** Whether or not the notification sound was critical. */
  val critical: Boolean,
  /** The resource name of the sound played. */
  val name: String? = null,
  /**
   * The volume of the sound.
   *
   * This value is a number between 0.0 & 1.0.
   */
  val volume: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KlaviyoAppleNotificationSound {
      val critical = pigeonVar_list[0] as Boolean
      val name = pigeonVar_list[1] as String?
      val volume = pigeonVar_list[2] as Double
      return KlaviyoAppleNotificationSound(critical, name, volume)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      critical,
      name,
      volume,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KlaviyoAppleNotificationSound) {
      return false
    }
    if (this === other) {
      return true
    }
    return KlaviyoFlutterMessengerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Web specific properties of a [KlaviyoRemoteNotification].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KlaviyoWebNotification (
  /** Optional message label for custom analytics. */
  val analyticsLabel: String? = null,
  /**
   * The image URL for the notification.
   *
   * Will be `null` if the notification did not include an image.
   */
  val image: String? = null,
  /** The url which is typically being navigated to when the notification is clicked. */
  val link: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KlaviyoWebNotification {
      val analyticsLabel = pigeonVar_list[0] as String?
      val image = pigeonVar_list[1] as String?
      val link = pigeonVar_list[2] as String?
      return KlaviyoWebNotification(analyticsLabel, image, link)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      analyticsLabel,
      image,
      link,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KlaviyoWebNotification) {
      return false
    }
    if (this === other) {
      return true
    }
    return KlaviyoFlutterMessengerPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class KlaviyoFlutterMessengerPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KlaviyoAppleNotificationSetting.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KlaviyoAppleShowPreviewSetting.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KlaviyoAuthorizationStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KlaviyoAndroidNotificationPriority.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KlaviyoRemoteMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KlaviyoRemoteNotification.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KlaviyoAndroidNotification.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KlaviyoAppleNotification.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KlaviyoAppleNotificationSound.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KlaviyoWebNotification.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KlaviyoAppleNotificationSetting -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is KlaviyoAppleShowPreviewSetting -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is KlaviyoAuthorizationStatus -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is KlaviyoAndroidNotificationPriority -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is KlaviyoRemoteMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is KlaviyoRemoteNotification -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is KlaviyoAndroidNotification -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is KlaviyoAppleNotification -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is KlaviyoAppleNotificationSound -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is KlaviyoWebNotification -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val KlaviyoFlutterMessengerPigeonMethodCodec = StandardMethodCodec(KlaviyoFlutterMessengerPigeonCodec())


private class KlaviyoFlutterMessengerPigeonStreamHandler<T>(
    val wrapper: KlaviyoFlutterMessengerPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface KlaviyoFlutterMessengerPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class OnMessageStreamHandler : KlaviyoFlutterMessengerPigeonEventChannelWrapper<KlaviyoRemoteMessage> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnMessageStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.pigeon_example_package.KlaviyoFlutterMessenger.onMessage"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = KlaviyoFlutterMessengerPigeonStreamHandler<KlaviyoRemoteMessage>(streamHandler)
      EventChannel(messenger, channelName, KlaviyoFlutterMessengerPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class OnMessageOpenedAppStreamHandler : KlaviyoFlutterMessengerPigeonEventChannelWrapper<KlaviyoRemoteMessage> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: OnMessageOpenedAppStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.pigeon_example_package.KlaviyoFlutterMessenger.onMessageOpenedApp"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = KlaviyoFlutterMessengerPigeonStreamHandler<KlaviyoRemoteMessage>(streamHandler)
      EventChannel(messenger, channelName, KlaviyoFlutterMessengerPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
