// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsKlaviyoFlutterMessenger(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsKlaviyoFlutterMessenger(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsKlaviyoFlutterMessenger(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashKlaviyoFlutterMessenger(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashKlaviyoFlutterMessenger(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashKlaviyoFlutterMessenger(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// An enum representing a notification setting for this app on the device.
enum KlaviyoAppleNotificationSetting: Int {
  /// This setting is currently disabled by the user.
  case disabled = 0
  /// This setting is currently enabled.
  case enabled = 1
  /// This setting is not supported on this device.
  ///
  /// Usually this means that the iOS version required for this setting has not been met,
  /// or the platform is not Apple.
  case notSupported = 2
}

/// An enum representing the show previews notification setting for this app on the device.
enum KlaviyoAppleShowPreviewSetting: Int {
  /// Always show previews even if the device is currently locked.
  case always = 0
  /// Never show previews.
  case never = 1
  /// This setting is not supported on this device.
  ///
  /// Usually this means that the iOS version required for this setting (iOS 11+) has not been met,
  /// or the platform is not Apple.
  case notSupported = 2
  /// Only show previews when the device is unlocked.
  case whenAuthenticated = 3
}

/// Represents the current status of the platforms notification permissions.
enum KlaviyoAuthorizationStatus: Int {
  /// The app is authorized to create notifications.
  case authorized = 0
  /// The app is not authorized to create notifications.
  case denied = 1
  /// The app user has not yet chosen whether to allow the application to create
  /// notifications. Usually this status is returned prior to the first call
  /// of [requestPermission].
  case notDetermined = 2
  /// The app is currently authorized to post non-interrupting user notifications.
  case provisional = 3
}

/// An enum representing a notification priority on Android.
///
/// Note; on devices which have channel support (Android 8.0 (API level 26) +),
/// this value will be ignored. Instead, the channel "importance" level is used.
enum KlaviyoAndroidNotificationPriority: Int {
  /// The application small icon will not show up in the status bar, or alert the user. The notification
  /// will be in a collapsed state in the notification shade and placed at the bottom of the list.
  case minimumPriority = 0
  /// The application small icon will show in the device status bar, however the notification will
  /// not alert the user (no sound or vibration). The notification will show in it's expanded state
  /// when the notification shade is pulled down.
  case lowPriority = 1
  /// When a notification is received, the device smallIcon will appear in the notification shade.
  /// When the user pulls down the notification shade, the content of the notification will be shown
  /// in it's expanded state.
  case defaultPriority = 2
  /// Notifications will appear on-top of applications, allowing direct interaction without pulling
  /// own the notification shade. This level is used for urgent notifications, such as
  /// incoming phone calls, messages etc, which require immediate attention.
  case highPriority = 3
  /// The highest priority level a notification can be set to.
  case maximumPriority = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct KlaviyoRemoteMessage: Hashable {
  /// The ID of the upstream sender location.
  var senderId: String? = nil
  /// The iOS category this notification is assigned to.
  var category: String? = nil
  /// The collapse key a message was sent with. Used to override existing messages with the same key.
  var collapseKey: String? = nil
  /// Whether the iOS APNs message was configured as a background update notification.
  var contentAvailable: Bool
  /// Any additional data sent with the message.
  var data: [String?: Any?]
  /// The topic name or message identifier.
  var from: String? = nil
  /// A unique ID assigned to every message.
  var messageId: String? = nil
  /// The message type of the message.
  var messageType: String? = nil
  /// Whether the iOS APNs `mutable-content` property on the message was set
  /// allowing the app to modify the notification via app extensions.
  var mutableContent: Bool
  /// Additional Notification data sent with the message.
  var notification: KlaviyoRemoteNotification? = nil
  /// The time the message was sent, represented as a [String].
  var sentTime: String? = nil
  /// An iOS app specific identifier used for notification grouping.
  var threadId: String? = nil
  /// The time to live for the message in seconds.
  var ttl: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KlaviyoRemoteMessage? {
    let senderId: String? = nilOrValue(pigeonVar_list[0])
    let category: String? = nilOrValue(pigeonVar_list[1])
    let collapseKey: String? = nilOrValue(pigeonVar_list[2])
    let contentAvailable = pigeonVar_list[3] as! Bool
    let data = pigeonVar_list[4] as! [String?: Any?]
    let from: String? = nilOrValue(pigeonVar_list[5])
    let messageId: String? = nilOrValue(pigeonVar_list[6])
    let messageType: String? = nilOrValue(pigeonVar_list[7])
    let mutableContent = pigeonVar_list[8] as! Bool
    let notification: KlaviyoRemoteNotification? = nilOrValue(pigeonVar_list[9])
    let sentTime: String? = nilOrValue(pigeonVar_list[10])
    let threadId: String? = nilOrValue(pigeonVar_list[11])
    let ttl: Int64? = nilOrValue(pigeonVar_list[12])

    return KlaviyoRemoteMessage(
      senderId: senderId,
      category: category,
      collapseKey: collapseKey,
      contentAvailable: contentAvailable,
      data: data,
      from: from,
      messageId: messageId,
      messageType: messageType,
      mutableContent: mutableContent,
      notification: notification,
      sentTime: sentTime,
      threadId: threadId,
      ttl: ttl
    )
  }
  func toList() -> [Any?] {
    return [
      senderId,
      category,
      collapseKey,
      contentAvailable,
      data,
      from,
      messageId,
      messageType,
      mutableContent,
      notification,
      sentTime,
      threadId,
      ttl,
    ]
  }
  static func == (lhs: KlaviyoRemoteMessage, rhs: KlaviyoRemoteMessage) -> Bool {
    return deepEqualsKlaviyoFlutterMessenger(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKlaviyoFlutterMessenger(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KlaviyoRemoteNotification: Hashable {
  /// Android specific notification properties.
  var android: KlaviyoAndroidNotification? = nil
  /// Apple specific notification properties.
  var apple: KlaviyoAppleNotification? = nil
  /// Web specific notification properties.
  var web: KlaviyoWebNotification? = nil
  /// The notification title.
  var title: String? = nil
  /// Any arguments that should be formatted into the resource specified by titleLocKey.
  var titleLocArgs: [String]
  /// The native localization key for the notification title.
  var titleLocKey: String? = nil
  /// The notification body content.
  var body: String? = nil
  /// Any arguments that should be formatted into the resource specified by bodyLocKey.
  var bodyLocArgs: [String]
  /// The native localization key for the notification body content.
  var bodyLocKey: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KlaviyoRemoteNotification? {
    let android: KlaviyoAndroidNotification? = nilOrValue(pigeonVar_list[0])
    let apple: KlaviyoAppleNotification? = nilOrValue(pigeonVar_list[1])
    let web: KlaviyoWebNotification? = nilOrValue(pigeonVar_list[2])
    let title: String? = nilOrValue(pigeonVar_list[3])
    let titleLocArgs = pigeonVar_list[4] as! [String]
    let titleLocKey: String? = nilOrValue(pigeonVar_list[5])
    let body: String? = nilOrValue(pigeonVar_list[6])
    let bodyLocArgs = pigeonVar_list[7] as! [String]
    let bodyLocKey: String? = nilOrValue(pigeonVar_list[8])

    return KlaviyoRemoteNotification(
      android: android,
      apple: apple,
      web: web,
      title: title,
      titleLocArgs: titleLocArgs,
      titleLocKey: titleLocKey,
      body: body,
      bodyLocArgs: bodyLocArgs,
      bodyLocKey: bodyLocKey
    )
  }
  func toList() -> [Any?] {
    return [
      android,
      apple,
      web,
      title,
      titleLocArgs,
      titleLocKey,
      body,
      bodyLocArgs,
      bodyLocKey,
    ]
  }
  static func == (lhs: KlaviyoRemoteNotification, rhs: KlaviyoRemoteNotification) -> Bool {
    return deepEqualsKlaviyoFlutterMessenger(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKlaviyoFlutterMessenger(value: toList(), hasher: &hasher)
  }
}

/// Android specific properties of a [KlaviyoRemoteNotification].
///
/// This will only be populated if the current device is Android.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KlaviyoAndroidNotification: Hashable {
  /// The channel the notification is delivered on.
  var channelId: String? = nil
  /// A spcific click action was defined for the notification.
  ///
  /// This property is not required to handle user interaction.
  var clickAction: String? = nil
  /// The color of the notification.
  var color: String? = nil
  /// The current notification count for the application.
  var count: Int64? = nil
  /// The image URL for the notification.
  ///
  /// Will be `null` if the notification did not include an image.
  var imageUrl: String? = nil
  var link: String? = nil
  /// The priority for the notifcation.
  ///
  /// This property only has impact on devices running Android 8.0 (API level 26) +.
  /// Later than this, they use the channel importance instead.
  var priority: KlaviyoAndroidNotificationPriority
  /// The resource file name of the small icon shown in the notification.
  var smallIcon: String? = nil
  /// The resource file name of the sound used to alert users to the incoming notification.
  var sound: String? = nil
  /// Ticker text for the notification, used for accessibility purposes.
  var ticker: String? = nil
  /// The tag of the notification.
  var tag: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KlaviyoAndroidNotification? {
    let channelId: String? = nilOrValue(pigeonVar_list[0])
    let clickAction: String? = nilOrValue(pigeonVar_list[1])
    let color: String? = nilOrValue(pigeonVar_list[2])
    let count: Int64? = nilOrValue(pigeonVar_list[3])
    let imageUrl: String? = nilOrValue(pigeonVar_list[4])
    let link: String? = nilOrValue(pigeonVar_list[5])
    let priority = pigeonVar_list[6] as! KlaviyoAndroidNotificationPriority
    let smallIcon: String? = nilOrValue(pigeonVar_list[7])
    let sound: String? = nilOrValue(pigeonVar_list[8])
    let ticker: String? = nilOrValue(pigeonVar_list[9])
    let tag: String? = nilOrValue(pigeonVar_list[10])

    return KlaviyoAndroidNotification(
      channelId: channelId,
      clickAction: clickAction,
      color: color,
      count: count,
      imageUrl: imageUrl,
      link: link,
      priority: priority,
      smallIcon: smallIcon,
      sound: sound,
      ticker: ticker,
      tag: tag
    )
  }
  func toList() -> [Any?] {
    return [
      channelId,
      clickAction,
      color,
      count,
      imageUrl,
      link,
      priority,
      smallIcon,
      sound,
      ticker,
      tag,
    ]
  }
  static func == (lhs: KlaviyoAndroidNotification, rhs: KlaviyoAndroidNotification) -> Bool {
    return deepEqualsKlaviyoFlutterMessenger(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKlaviyoFlutterMessenger(value: toList(), hasher: &hasher)
  }
}

/// Apple specific properties of a [KlaviyoRemoteNotification].
///
/// This will only be populated if the current device is Apple based (iOS/MacOS).
///
/// Generated class from Pigeon that represents data sent in messages.
struct KlaviyoAppleNotification: Hashable {
  /// The value which sets the application badge.
  var badge: String? = nil
  /// Sound values for the incoming notification.
  var sound: KlaviyoAppleNotificationSound? = nil
  /// The image URL for the notification.
  ///
  /// Will be `null` if the notification did not include an image.
  var imageUrl: String? = nil
  /// Any subtile text on the notification.
  var subtitle: String? = nil
  /// Any arguments that should be formatted into the resource specified by subtitleLocKey.
  var subtitleLocArgs: [String]
  /// The native localization key for the notification subtitle.
  var subtitleLocKey: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KlaviyoAppleNotification? {
    let badge: String? = nilOrValue(pigeonVar_list[0])
    let sound: KlaviyoAppleNotificationSound? = nilOrValue(pigeonVar_list[1])
    let imageUrl: String? = nilOrValue(pigeonVar_list[2])
    let subtitle: String? = nilOrValue(pigeonVar_list[3])
    let subtitleLocArgs = pigeonVar_list[4] as! [String]
    let subtitleLocKey: String? = nilOrValue(pigeonVar_list[5])

    return KlaviyoAppleNotification(
      badge: badge,
      sound: sound,
      imageUrl: imageUrl,
      subtitle: subtitle,
      subtitleLocArgs: subtitleLocArgs,
      subtitleLocKey: subtitleLocKey
    )
  }
  func toList() -> [Any?] {
    return [
      badge,
      sound,
      imageUrl,
      subtitle,
      subtitleLocArgs,
      subtitleLocKey,
    ]
  }
  static func == (lhs: KlaviyoAppleNotification, rhs: KlaviyoAppleNotification) -> Bool {
    return deepEqualsKlaviyoFlutterMessenger(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKlaviyoFlutterMessenger(value: toList(), hasher: &hasher)
  }
}

/// Represents the sound property for [KlaviyoAppleNotification]
///
/// Generated class from Pigeon that represents data sent in messages.
struct KlaviyoAppleNotificationSound: Hashable {
  /// Whether or not the notification sound was critical.
  var critical: Bool
  /// The resource name of the sound played.
  var name: String? = nil
  /// The volume of the sound.
  ///
  /// This value is a number between 0.0 & 1.0.
  var volume: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KlaviyoAppleNotificationSound? {
    let critical = pigeonVar_list[0] as! Bool
    let name: String? = nilOrValue(pigeonVar_list[1])
    let volume = pigeonVar_list[2] as! Double

    return KlaviyoAppleNotificationSound(
      critical: critical,
      name: name,
      volume: volume
    )
  }
  func toList() -> [Any?] {
    return [
      critical,
      name,
      volume,
    ]
  }
  static func == (lhs: KlaviyoAppleNotificationSound, rhs: KlaviyoAppleNotificationSound) -> Bool {
    return deepEqualsKlaviyoFlutterMessenger(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKlaviyoFlutterMessenger(value: toList(), hasher: &hasher)
  }
}

/// Web specific properties of a [KlaviyoRemoteNotification].
///
/// Generated class from Pigeon that represents data sent in messages.
struct KlaviyoWebNotification: Hashable {
  /// Optional message label for custom analytics.
  var analyticsLabel: String? = nil
  /// The image URL for the notification.
  ///
  /// Will be `null` if the notification did not include an image.
  var image: String? = nil
  /// The url which is typically being navigated to when the notification is clicked.
  var link: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KlaviyoWebNotification? {
    let analyticsLabel: String? = nilOrValue(pigeonVar_list[0])
    let image: String? = nilOrValue(pigeonVar_list[1])
    let link: String? = nilOrValue(pigeonVar_list[2])

    return KlaviyoWebNotification(
      analyticsLabel: analyticsLabel,
      image: image,
      link: link
    )
  }
  func toList() -> [Any?] {
    return [
      analyticsLabel,
      image,
      link,
    ]
  }
  static func == (lhs: KlaviyoWebNotification, rhs: KlaviyoWebNotification) -> Bool {
    return deepEqualsKlaviyoFlutterMessenger(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashKlaviyoFlutterMessenger(value: toList(), hasher: &hasher)
  }
}

private class KlaviyoFlutterMessengerPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KlaviyoAppleNotificationSetting(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KlaviyoAppleShowPreviewSetting(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KlaviyoAuthorizationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KlaviyoAndroidNotificationPriority(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return KlaviyoRemoteMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return KlaviyoRemoteNotification.fromList(self.readValue() as! [Any?])
    case 135:
      return KlaviyoAndroidNotification.fromList(self.readValue() as! [Any?])
    case 136:
      return KlaviyoAppleNotification.fromList(self.readValue() as! [Any?])
    case 137:
      return KlaviyoAppleNotificationSound.fromList(self.readValue() as! [Any?])
    case 138:
      return KlaviyoWebNotification.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class KlaviyoFlutterMessengerPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KlaviyoAppleNotificationSetting {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KlaviyoAppleShowPreviewSetting {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? KlaviyoAuthorizationStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? KlaviyoAndroidNotificationPriority {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? KlaviyoRemoteMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? KlaviyoRemoteNotification {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? KlaviyoAndroidNotification {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? KlaviyoAppleNotification {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? KlaviyoAppleNotificationSound {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? KlaviyoWebNotification {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class KlaviyoFlutterMessengerPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return KlaviyoFlutterMessengerPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return KlaviyoFlutterMessengerPigeonCodecWriter(data: data)
  }
}

class KlaviyoFlutterMessengerPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = KlaviyoFlutterMessengerPigeonCodec(readerWriter: KlaviyoFlutterMessengerPigeonCodecReaderWriter())
}

var klaviyoFlutterMessengerPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: KlaviyoFlutterMessengerPigeonCodecReaderWriter());


private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class OnMessageStreamHandler: PigeonEventChannelWrapper<KlaviyoRemoteMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: OnMessageStreamHandler) {
    var channelName = "dev.flutter.pigeon.pigeon_example_package.KlaviyoFlutterMessenger.onMessage"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<KlaviyoRemoteMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: klaviyoFlutterMessengerPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class OnMessageOpenedAppStreamHandler: PigeonEventChannelWrapper<KlaviyoRemoteMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: OnMessageOpenedAppStreamHandler) {
    var channelName = "dev.flutter.pigeon.pigeon_example_package.KlaviyoFlutterMessenger.onMessageOpenedApp"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<KlaviyoRemoteMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: klaviyoFlutterMessengerPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
class OnTokenChangedStreamHandler: PigeonEventChannelWrapper<String> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: OnTokenChangedStreamHandler) {
    var channelName = "dev.flutter.pigeon.pigeon_example_package.KlaviyoFlutterMessenger.onTokenChanged"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<String>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: klaviyoFlutterMessengerPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
