// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// An enum representing a notification setting for this app on the device.
enum KlaviyoAppleNotificationSetting {
  /// This setting is currently disabled by the user.
  disabled,
  /// This setting is currently enabled.
  enabled,
  /// This setting is not supported on this device.
  ///
  /// Usually this means that the iOS version required for this setting has not been met,
  /// or the platform is not Apple.
  notSupported,
}

/// An enum representing the show previews notification setting for this app on the device.
enum KlaviyoAppleShowPreviewSetting {
  /// Always show previews even if the device is currently locked.
  always,
  /// Never show previews.
  never,
  /// This setting is not supported on this device.
  ///
  /// Usually this means that the iOS version required for this setting (iOS 11+) has not been met,
  /// or the platform is not Apple.
  notSupported,
  /// Only show previews when the device is unlocked.
  whenAuthenticated,
}

/// Represents the current status of the platforms notification permissions.
enum KlaviyoAuthorizationStatus {
  /// The app is authorized to create notifications.
  authorized,
  /// The app is not authorized to create notifications.
  denied,
  /// The app user has not yet chosen whether to allow the application to create
  /// notifications. Usually this status is returned prior to the first call
  /// of [requestPermission].
  notDetermined,
  /// The app is currently authorized to post non-interrupting user notifications.
  provisional,
}

/// An enum representing a notification priority on Android.
///
/// Note; on devices which have channel support (Android 8.0 (API level 26) +),
/// this value will be ignored. Instead, the channel "importance" level is used.
enum KlaviyoAndroidNotificationPriority {
  /// The application small icon will not show up in the status bar, or alert the user. The notification
  /// will be in a collapsed state in the notification shade and placed at the bottom of the list.
  minimumPriority,
  /// The application small icon will show in the device status bar, however the notification will
  /// not alert the user (no sound or vibration). The notification will show in it's expanded state
  /// when the notification shade is pulled down.
  lowPriority,
  /// When a notification is received, the device smallIcon will appear in the notification shade.
  /// When the user pulls down the notification shade, the content of the notification will be shown
  /// in it's expanded state.
  defaultPriority,
  /// Notifications will appear on-top of applications, allowing direct interaction without pulling
  /// own the notification shade. This level is used for urgent notifications, such as
  /// incoming phone calls, messages etc, which require immediate attention.
  highPriority,
  /// The highest priority level a notification can be set to.
  maximumPriority,
}

class KlaviyoRemoteMessage {
  KlaviyoRemoteMessage({
    this.senderId,
    this.category,
    this.collapseKey,
    required this.contentAvailable,
    required this.data,
    this.from,
    this.messageId,
    this.messageType,
    required this.mutableContent,
    this.notification,
    this.sentTime,
    this.threadId,
    this.ttl,
  });

  /// The ID of the upstream sender location.
  String? senderId;

  /// The iOS category this notification is assigned to.
  String? category;

  /// The collapse key a message was sent with. Used to override existing messages with the same key.
  String? collapseKey;

  /// Whether the iOS APNs message was configured as a background update notification.
  bool contentAvailable;

  /// Any additional data sent with the message.
  Map<String?, Object?> data;

  /// The topic name or message identifier.
  String? from;

  /// A unique ID assigned to every message.
  String? messageId;

  /// The message type of the message.
  String? messageType;

  /// Whether the iOS APNs `mutable-content` property on the message was set
  /// allowing the app to modify the notification via app extensions.
  bool mutableContent;

  /// Additional Notification data sent with the message.
  KlaviyoRemoteNotification? notification;

  /// The time the message was sent, represented as a [String].
  String? sentTime;

  /// An iOS app specific identifier used for notification grouping.
  String? threadId;

  /// The time to live for the message in seconds.
  int? ttl;

  List<Object?> _toList() {
    return <Object?>[
      senderId,
      category,
      collapseKey,
      contentAvailable,
      data,
      from,
      messageId,
      messageType,
      mutableContent,
      notification,
      sentTime,
      threadId,
      ttl,
    ];
  }

  Object encode() {
    return _toList();  }

  static KlaviyoRemoteMessage decode(Object result) {
    result as List<Object?>;
    return KlaviyoRemoteMessage(
      senderId: result[0] as String?,
      category: result[1] as String?,
      collapseKey: result[2] as String?,
      contentAvailable: result[3]! as bool,
      data: (result[4] as Map<Object?, Object?>?)!.cast<String?, Object?>(),
      from: result[5] as String?,
      messageId: result[6] as String?,
      messageType: result[7] as String?,
      mutableContent: result[8]! as bool,
      notification: result[9] as KlaviyoRemoteNotification?,
      sentTime: result[10] as String?,
      threadId: result[11] as String?,
      ttl: result[12] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KlaviyoRemoteMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class KlaviyoRemoteNotification {
  KlaviyoRemoteNotification({
    this.android,
    this.apple,
    this.web,
    this.title,
    required this.titleLocArgs,
    this.titleLocKey,
    this.body,
    required this.bodyLocArgs,
    this.bodyLocKey,
  });

  /// Android specific notification properties.
  KlaviyoAndroidNotification? android;

  /// Apple specific notification properties.
  KlaviyoAppleNotification? apple;

  /// Web specific notification properties.
  KlaviyoWebNotification? web;

  /// The notification title.
  String? title;

  /// Any arguments that should be formatted into the resource specified by titleLocKey.
  List<String> titleLocArgs;

  /// The native localization key for the notification title.
  String? titleLocKey;

  /// The notification body content.
  String? body;

  /// Any arguments that should be formatted into the resource specified by bodyLocKey.
  List<String> bodyLocArgs;

  /// The native localization key for the notification body content.
  String? bodyLocKey;

  List<Object?> _toList() {
    return <Object?>[
      android,
      apple,
      web,
      title,
      titleLocArgs,
      titleLocKey,
      body,
      bodyLocArgs,
      bodyLocKey,
    ];
  }

  Object encode() {
    return _toList();  }

  static KlaviyoRemoteNotification decode(Object result) {
    result as List<Object?>;
    return KlaviyoRemoteNotification(
      android: result[0] as KlaviyoAndroidNotification?,
      apple: result[1] as KlaviyoAppleNotification?,
      web: result[2] as KlaviyoWebNotification?,
      title: result[3] as String?,
      titleLocArgs: (result[4] as List<Object?>?)!.cast<String>(),
      titleLocKey: result[5] as String?,
      body: result[6] as String?,
      bodyLocArgs: (result[7] as List<Object?>?)!.cast<String>(),
      bodyLocKey: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KlaviyoRemoteNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Android specific properties of a [KlaviyoRemoteNotification].
///
/// This will only be populated if the current device is Android.
class KlaviyoAndroidNotification {
  KlaviyoAndroidNotification({
    this.channelId,
    this.clickAction,
    this.color,
    this.count,
    this.imageUrl,
    this.link,
    required this.priority,
    this.smallIcon,
    this.sound,
    this.ticker,
    this.tag,
  });

  /// The channel the notification is delivered on.
  String? channelId;

  /// A spcific click action was defined for the notification.
  ///
  /// This property is not required to handle user interaction.
  String? clickAction;

  /// The color of the notification.
  String? color;

  /// The current notification count for the application.
  int? count;

  /// The image URL for the notification.
  ///
  /// Will be `null` if the notification did not include an image.
  String? imageUrl;

  String? link;

  /// The priority for the notifcation.
  ///
  /// This property only has impact on devices running Android 8.0 (API level 26) +.
  /// Later than this, they use the channel importance instead.
  KlaviyoAndroidNotificationPriority priority;

  /// The resource file name of the small icon shown in the notification.
  String? smallIcon;

  /// The resource file name of the sound used to alert users to the incoming notification.
  String? sound;

  /// Ticker text for the notification, used for accessibility purposes.
  String? ticker;

  /// The tag of the notification.
  String? tag;

  List<Object?> _toList() {
    return <Object?>[
      channelId,
      clickAction,
      color,
      count,
      imageUrl,
      link,
      priority,
      smallIcon,
      sound,
      ticker,
      tag,
    ];
  }

  Object encode() {
    return _toList();  }

  static KlaviyoAndroidNotification decode(Object result) {
    result as List<Object?>;
    return KlaviyoAndroidNotification(
      channelId: result[0] as String?,
      clickAction: result[1] as String?,
      color: result[2] as String?,
      count: result[3] as int?,
      imageUrl: result[4] as String?,
      link: result[5] as String?,
      priority: result[6]! as KlaviyoAndroidNotificationPriority,
      smallIcon: result[7] as String?,
      sound: result[8] as String?,
      ticker: result[9] as String?,
      tag: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KlaviyoAndroidNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Apple specific properties of a [KlaviyoRemoteNotification].
///
/// This will only be populated if the current device is Apple based (iOS/MacOS).
class KlaviyoAppleNotification {
  KlaviyoAppleNotification({
    this.badge,
    this.sound,
    this.imageUrl,
    this.subtitle,
    required this.subtitleLocArgs,
    this.subtitleLocKey,
  });

  /// The value which sets the application badge.
  String? badge;

  /// Sound values for the incoming notification.
  KlaviyoAppleNotificationSound? sound;

  /// The image URL for the notification.
  ///
  /// Will be `null` if the notification did not include an image.
  String? imageUrl;

  /// Any subtile text on the notification.
  String? subtitle;

  /// Any arguments that should be formatted into the resource specified by subtitleLocKey.
  List<String> subtitleLocArgs;

  /// The native localization key for the notification subtitle.
  String? subtitleLocKey;

  List<Object?> _toList() {
    return <Object?>[
      badge,
      sound,
      imageUrl,
      subtitle,
      subtitleLocArgs,
      subtitleLocKey,
    ];
  }

  Object encode() {
    return _toList();  }

  static KlaviyoAppleNotification decode(Object result) {
    result as List<Object?>;
    return KlaviyoAppleNotification(
      badge: result[0] as String?,
      sound: result[1] as KlaviyoAppleNotificationSound?,
      imageUrl: result[2] as String?,
      subtitle: result[3] as String?,
      subtitleLocArgs: (result[4] as List<Object?>?)!.cast<String>(),
      subtitleLocKey: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KlaviyoAppleNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents the sound property for [KlaviyoAppleNotification]
class KlaviyoAppleNotificationSound {
  KlaviyoAppleNotificationSound({
    required this.critical,
    this.name,
    required this.volume,
  });

  /// Whether or not the notification sound was critical.
  bool critical;

  /// The resource name of the sound played.
  String? name;

  /// The volume of the sound.
  ///
  /// This value is a number between 0.0 & 1.0.
  double volume;

  List<Object?> _toList() {
    return <Object?>[
      critical,
      name,
      volume,
    ];
  }

  Object encode() {
    return _toList();  }

  static KlaviyoAppleNotificationSound decode(Object result) {
    result as List<Object?>;
    return KlaviyoAppleNotificationSound(
      critical: result[0]! as bool,
      name: result[1] as String?,
      volume: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KlaviyoAppleNotificationSound || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Web specific properties of a [KlaviyoRemoteNotification].
class KlaviyoWebNotification {
  KlaviyoWebNotification({
    this.analyticsLabel,
    this.image,
    this.link,
  });

  /// Optional message label for custom analytics.
  String? analyticsLabel;

  /// The image URL for the notification.
  ///
  /// Will be `null` if the notification did not include an image.
  String? image;

  /// The url which is typically being navigated to when the notification is clicked.
  String? link;

  List<Object?> _toList() {
    return <Object?>[
      analyticsLabel,
      image,
      link,
    ];
  }

  Object encode() {
    return _toList();  }

  static KlaviyoWebNotification decode(Object result) {
    result as List<Object?>;
    return KlaviyoWebNotification(
      analyticsLabel: result[0] as String?,
      image: result[1] as String?,
      link: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KlaviyoWebNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is KlaviyoAppleNotificationSetting) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is KlaviyoAppleShowPreviewSetting) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is KlaviyoAuthorizationStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is KlaviyoAndroidNotificationPriority) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is KlaviyoRemoteMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is KlaviyoRemoteNotification) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is KlaviyoAndroidNotification) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is KlaviyoAppleNotification) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is KlaviyoAppleNotificationSound) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is KlaviyoWebNotification) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KlaviyoAppleNotificationSetting.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KlaviyoAppleShowPreviewSetting.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KlaviyoAuthorizationStatus.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : KlaviyoAndroidNotificationPriority.values[value];
      case 133: 
        return KlaviyoRemoteMessage.decode(readValue(buffer)!);
      case 134: 
        return KlaviyoRemoteNotification.decode(readValue(buffer)!);
      case 135: 
        return KlaviyoAndroidNotification.decode(readValue(buffer)!);
      case 136: 
        return KlaviyoAppleNotification.decode(readValue(buffer)!);
      case 137: 
        return KlaviyoAppleNotificationSound.decode(readValue(buffer)!);
      case 138: 
        return KlaviyoWebNotification.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

Stream<KlaviyoRemoteMessage> onMessage( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onMessageChannel =
      EventChannel('dev.flutter.pigeon.klaviyo_flutter.KlaviyoFlutterMessenger.onMessage$instanceName', pigeonMethodCodec);
  return onMessageChannel.receiveBroadcastStream().map((dynamic event) {
    return event as KlaviyoRemoteMessage;
  });
}
    
Stream<KlaviyoRemoteMessage> onMessageOpenedApp( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onMessageOpenedAppChannel =
      EventChannel('dev.flutter.pigeon.klaviyo_flutter.KlaviyoFlutterMessenger.onMessageOpenedApp$instanceName', pigeonMethodCodec);
  return onMessageOpenedAppChannel.receiveBroadcastStream().map((dynamic event) {
    return event as KlaviyoRemoteMessage;
  });
}
    
Stream<String> onTokenChanged( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel onTokenChangedChannel =
      EventChannel('dev.flutter.pigeon.klaviyo_flutter.KlaviyoFlutterMessenger.onTokenChanged$instanceName', pigeonMethodCodec);
  return onTokenChangedChannel.receiveBroadcastStream().map((dynamic event) {
    return event as String;
  });
}
    
